version: "3"
services:
  softether-bridge:
    image: sammrai/softether-bridge:latest
    container_name: softether-bridge
    environment:
      - USERNAME=vpnname
      - PASSWORD=vpnpassword
      - PSK=vpnsecret
      - VPN_SERVER=host.docker.internal:5555
    networks:
      app_net:
        ipv4_address: 172.30.0.2
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    networks:
      app_net:
        ipv4_address: 172.30.0.3
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24
